### ISSUE TITLE
[BUG] Offlineshop broken (?, report missing information)

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lnbits/offlineshop#7]
**Describe the bug**
<img width="658" alt="image" src="https://github.com/lnbits/lnbits/assets/93607398/f3494a69-9eef-4899-aa67-a3fabf59097f">

Currently LNURLp is not working, neither in LNURLp plugin nor in offline shop, so it seems to be a deeper issue. Tested on my own instance and Legends.

- LNbits version: 0.11.1

**Comment by prusnak** [comment]
> Offline shop is completely broken, as shown in the screenshot.

Moved the issue to the offlineshop repo then.

**Comment by callebtc** [comment]
> Offline shop is completely broken

Please post the output of your LNbits terminal so we can figure out what went wrong here. Thanks!

**Comment by MichaelAntonFischer** [comment]
![image](https://github.com/lnbits/offlineshop/assets/93607398/5e219a7b-e998-4c42-b844-4cec07603d76)
That’s the only output, basically the same as the screenshot. This is after using fjatjafs decoder, because wallets don’t even decode it. Same issue with legends.
